apiVersion: serving.knative.dev/v1
kind: Service
metadata:
    name: notes-api
    namespace: notes-api-468412
spec:
    template:
        metadata:
        spec:
            containers:
                - image: europe-west4-docker.pkg.dev/notes-api-468412/notesapi-repo/notes-api
                  env:
                      - name: CLOUD_DB_URL
                        valueFrom:
                            secretKeyRef:
                                name: cloud-db-url
                                key: latest
